// End-to-end walkthrough of both experiences against a running preview (npm run preview).
// Requires: npm i -D playwright && npx playwright install chromium. Screenshots land in smoke-shots/.
import { chromium } from 'playwright';
import fs from 'node:fs';
const BASE = (process.env.BASE_URL ?? 'http://localhost:4173') + '/#';
const shots = new URL('../smoke-shots/', import.meta.url).pathname;
fs.mkdirSync(shots, { recursive: true });
const browser = await chromium.launch({ headless: true, ...(process.env.CHROMIUM_PATH ? { executablePath: process.env.CHROMIUM_PATH } : {}) });
const ctx = await browser.newContext({ viewport: { width: 1440, height: 900 }, acceptDownloads: true });
const page = await ctx.newPage();
const errors = [];
page.on('pageerror', (e) => errors.push('pageerror: ' + e.message));
page.on('console', (m) => { if (m.type() === 'error') errors.push('console: ' + m.text()); });
const shot = (n) => page.screenshot({ path: `${shots}/${n}.png`, fullPage: false });
const step = async (name, fn) => { try { await fn(); console.log('✓', name); } catch (e) { console.log('✗', name, '-', e.message.split('\n')[0]); await shot('FAIL-' + name.replace(/\W+/g, '_')); throw e; } };
const switchTo = async (role, userLabel) => {
  await page.click('.demo-fab');
  const sel = role === 'office' ? page.locator('.demo-panel select').nth(0) : page.locator('.demo-panel select').nth(1);
  await sel.selectOption({ label: userLabel });
  await page.waitForTimeout(300);
};

await step('entry screen renders', async () => {
  await page.goto(BASE + '/');
  await page.waitForSelector('text=One application. Two ways in.');
  await shot('01-entry');
});
await step('office: enter as Maya Chen', async () => {
  await page.selectOption('#office-persona', 'u_maya');
  await page.click('text=Open the office experience');
  await page.waitForSelector('text=Request Management');
  await shot('02-office-requests');
});
await step('office: add patient and referral', async () => {
  await page.click('text=Patient', { timeout: 5000 });
  await page.waitForSelector('text=Patients');
  await page.click('text=Add patient & referral');
  await page.waitForSelector('text=Add patient and referral');
  const f = async (label, value) => { const el = page.locator(`.field:has(label:has-text("${label}")) input, .field:has(label:has-text("${label}")) textarea`).first(); await el.fill(value); };
  await f('First name', 'Rosa'); await f('Last name', 'Delacroix'); await f('Date of birth', '1949-04-12'); await f('MRN', 'BHH-20555'); await f('Phone', '(510) 555-0399'); await f('Street address', '4400 Central Ave, Apt 3'); await f('ZIP', '94536');
  await page.locator('.field:has(label:has-text("Notes to clinicians")) textarea').fill('PT SOC this week. Spanish speaking.');
  await page.locator('.field:has(label:has-text("Case-management notes")) textarea').fill('PT SOC after knee replacement.');
  await shot('03-new-patient');
  await page.click('text=Save and create visit request');
  await page.waitForSelector('text=New visit request');
});
await step('office: request info → select clinicians', async () => {
  await page.waitForSelector('text=Rosa Delacroix');
  await page.click('text=Next: select clinicians');
  await page.waitForSelector('text=Eligible clinicians');
  await shot('04-select-clinicians');
  const rows = await page.locator('.cand-row').count();
  if (rows < 2) throw new Error('expected candidates for PT in 94536');
  const blocked = await page.locator('.cand-row.blocked').count();
  if (blocked < 1) throw new Error('Daniel Okafor should be shown as credential-blocked');
  const disabledChecked = await page.locator('.cand-row.blocked input:disabled').count();
  if (disabledChecked < 1) throw new Error('blocked clinician checkbox should be disabled');
  await page.click('text=Next: review');
  await page.waitForSelector('text=Selected clinicians');
  await shot('05-review-send');
  await page.click('button:has-text("Send request")');
  await page.waitForSelector('text=Request log');
  await shot('06-request-detail-pending');
});
const url = page.url();
const reqId = url.split('/requests/')[1];
console.log('   request id', reqId);
await step('clinician: Priya accepts (FCFS assigns)', async () => {
  await switchTo('clinician', 'Priya Natarajan (PT)');
  await page.waitForSelector('text=Hi, Priya');
  await shot('07-clinician-home');
  await page.click('.nav-links >> text=Requests');
  await page.waitForSelector('text=FIRST TO RESPOND');
  const card = page.locator('.card:has-text("Fremont, CA 94536"):has-text("Spanish speaking")').first();
  const body = await page.innerText('body');
  if (body.includes('4400 Central') || body.includes('Delacroix')) throw new Error('patient name/street must be hidden before assignment');
  await card.locator('button:has-text("Available")').first().click();
  await page.waitForSelector('text=Rosa Delacroix');
  await page.waitForSelector('text=Patient chat');
  await shot('08-clinician-assigned-patient');
});
await step('office: assignment visible, schedule plot', async () => {
  await switchTo('office', 'Maya Chen - Intake Coordinator');
  await page.goto(BASE + `/office/scheduling/requests/${reqId}`);
  await page.waitForSelector('text=Assigned to Priya Natarajan');
  await shot('09-request-assigned');
  await page.goto(BASE + '/office/scheduling/schedule');
  await page.waitForSelector('text=Schedule');
  const row = page.locator('tr:has-text("Delacroix")').first();
  await row.click();
  await page.waitForSelector('text=Planned visit date');
  const today = new Date().toISOString().slice(0, 10);
  await page.locator('.drawer input[type=date]').fill(today);
  await page.locator('.drawer select').first().selectOption('plotted');
  await page.locator('.drawer textarea').fill('Agency CM confirmed plot.');
  await page.click('.drawer button:has-text("Save")');
  await page.waitForSelector('text=Schedule updated');
  await shot('10-schedule');
});
await step('clinician: confirm visit and submit billing', async () => {
  await switchTo('clinician', 'Priya Natarajan (PT)');
  await page.goto(BASE + '/clinician/schedule');
  await page.locator('a.list-item:has-text("Delacroix")').first().click();
  await page.waitForSelector('text=Confirm completed work');
  const checks = page.locator('.drawer .check input');
  await checks.nth(0).check(); await checks.nth(1).check();
  await page.waitForSelector('text=Submit this visit for billing');
  await page.click('.drawer button:has-text("Submit for billing")');
  await page.waitForSelector('text=Your rate (pre-filled)');
  await page.locator('.drawer textarea').fill('SOC completed; freq 2w4.');
  await shot('11-clinician-submit-billing');
  await page.click('.drawer button:has-text("Submit"):not(:has-text("for"))');
  await page.waitForSelector('text=Submitted for billing review');
  await page.waitForSelector('text=Awaiting review');
  await shot('12-clinician-billing');
});
await step('office: review, approve, batch, export, pay', async () => {
  await switchTo('office', 'Sam Patel - Billing Specialist');
  await page.goto(BASE + '/office/billing');
  await page.waitForSelector('text=Awaiting review');
  await page.locator('tr:has-text("Delacroix") button:has-text("Review")').click();
  await page.waitForSelector('text=Clinician pay rate');
  const txt = await page.locator('.drawer').innerText();
  if (!txt.includes('$120.00') || !txt.includes('$165.00')) throw new Error('expected clinician $120 and agency $165 rates: ' + txt.slice(0, 200));
  await shot('13-billing-review');
  await page.click('.drawer button:has-text("Approve")');
  await page.waitForSelector('text=both rates snapshotted');
  await page.goto(BASE + '/office/billing/agency');
  await page.waitForSelector('text=Prepare an agency invoice batch');
  await page.locator('button:has-text("Create invoice batch")').click();
  await page.waitForSelector('text=Invoice batch created');
  const [download] = await Promise.all([page.waitForEvent('download'), page.locator('button:has-text("Export file for QuickBooks")').first().click()]);
  const path = await download.path();
  const csv = fs.readFileSync(path, 'utf8');
  console.log('   csv first lines:\n   ' + csv.split('\r\n').slice(0, 2).join('\n   '));
  if (!csv.startsWith('InvoiceNo,Customer') || !csv.includes('Bayside Home Health') || !csv.includes('165.00')) throw new Error('unexpected csv');
  await page.waitForSelector('text=Exported');
  await shot('14-agency-export');
  await page.goto(BASE + '/office/billing/payments');
  await page.locator('tr:has-text("Delacroix") button:has-text("Update")').click();
  await page.locator('.modal select').selectOption('paid');
  await page.locator('.modal input[type=text], .modal input:not([type])').last().fill('ACH 88301');
  await page.click('.modal button:has-text("Save status")');
  await page.waitForSelector('text=Payout status updated');
  await shot('15-payments');
});
await step('clinician: sees paid status', async () => {
  await switchTo('clinician', 'Priya Natarajan (PT)');
  await page.goto(BASE + '/clinician/billing');
  await page.waitForSelector('tr:has-text("Delacroix") >> text=Paid');
  const body = await page.innerText('body');
  if (body.includes('165.00')) throw new Error('agency rate leaked to clinician');
  await shot('16-clinician-paid');
});
await step('credentials: Daniel blocked, uploads, office approves', async () => {
  await switchTo('clinician', 'Daniel Okafor (PT)');
  await page.goto(BASE + '/clinician/credentials');
  await page.waitForSelector('text=New requests are blocked');
  await shot('17-clinician-credentials-blocked');
  await page.locator('.list-item:has-text("CPR") button:has-text("Upload")').click();
  await page.locator('.modal input[type=file]').setInputFiles({ name: 'okafor-cpr-renewal.pdf', mimeType: 'application/pdf', buffer: Buffer.from('demo') });
  await page.click('.modal button:has-text("Submit for review")');
  await page.waitForSelector('text=the office will review');
  await switchTo('office', 'Lena Ortiz - HR & Credentialing');
  await page.goto(BASE + '/office/credentials');
  await page.waitForSelector('text=Onboarding & Credentials');
  await shot('18-office-credentials');
  await page.click('button:has-text("Awaiting review")');
  await page.locator('tr:has-text("Daniel Okafor") a:has-text("Review")').click();
  await page.waitForSelector('text=Required credentials');
  await page.locator('tr:has-text("CPR") button:has-text("Approve")').click();
  await page.click('.modal button:has-text("Approve")');
  await page.waitForSelector('text=eligibility recalculated');
  await page.waitForSelector('.pill:has-text("Ready")');
  await shot('19-office-credential-approved');
});
await step('reports and reset', async () => {
  await page.goto(BASE + '/office/reports');
  await page.waitForSelector('text=Requests by city');
  await shot('20-reports');
  await page.goto(BASE + '/office/regions');
  await page.waitForSelector('text=Coverage regions');
  await shot('21-regions');
  await switchTo('office', 'Maya Chen - Intake Coordinator');
  await page.goto(BASE + '/office/chat');
  await page.locator('.conv-item').first().click();
  await page.waitForSelector('.chat-msgs');
  await page.locator('.chat-compose textarea').fill('Plotted in Kinnser - you are good to go.');
  await page.click('.chat-compose button:has-text("Send")');
  await page.waitForSelector('.msg.mine >> text=good to go');
  await shot('22-chat');
  // refresh persistence
  await page.reload();
  await page.waitForSelector('.chat-msgs');
  await page.click('.demo-fab');
  await page.click('.demo-panel button:has-text("Reset demo")');
  await page.click('.modal button:has-text("Reset")');
  await page.waitForSelector('text=One application. Two ways in.');
});
// mobile clinician
await step('mobile clinician layout', async () => {
  const m = await browser.newContext({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true });
  const mp = m.newPage ? await m.newPage() : page;
  await mp.goto(BASE + '/');
  await mp.selectOption('#clin-persona', 'c_priya');
  await mp.click('text=Open the clinician experience');
  await mp.waitForSelector('text=Hi, Priya');
  await mp.screenshot({ path: `${shots}/23-mobile-home.png` });
  await mp.click('.tabbar >> text=Requests');
  await mp.waitForSelector('text=FIRST TO RESPOND');
  await mp.screenshot({ path: `${shots}/24-mobile-requests.png` });
  await mp.click('.tabbar >> text=Chat');
  await mp.locator('.conv-item').first().click();
  await mp.waitForSelector('.chat-msgs');
  await mp.screenshot({ path: `${shots}/25-mobile-chat.png` });
  const width = await mp.evaluate(() => document.documentElement.scrollWidth);
  if (width > 400) throw new Error('horizontal overflow on mobile: ' + width);
  await m.close();
});
console.log(errors.length ? 'ERRORS:\n' + errors.join('\n') : 'no console/page errors');
await browser.close();
